# Configuration for probot-auto-merge - https://github.com/bobvanderlinden/probot-auto-merge
minApprovals:
  NONE: 0
mergeMethod: squash
reportStatus: true
requiredLabels:
- automerge
mergeCommitMessage: "{title} (#{number})"
